# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZbQScdH28kKLVbNmrDBXgo_EG_LI5sp
"""

import streamlit as st
import pandas as pd
import joblib

# ===== MODEL =====
model = joblib.load("Фишинговая.pkl")

st.title("Проверка сайта на фишинг")

st.write("Оцените характеристики сайта (чем больше подозрительных признаков — тем выше риск)")

# ===== УНИВЕРСАЛЬНАЯ ФУНКЦИЯ =====
def feature(label, options_map):
    choice = st.selectbox(label, list(options_map.keys()))
    return options_map[choice]


# ===== ПРИЗНАКИ =====

UsingIP = feature(
    "Используется IP-адрес вместо домена?",
    {
        "Нет, используется домен": 1,
        "Нормально": 0,
        "Да, используется IP (подозрительно)": -1
    }
)

LongURL = feature(
    "Длина URL",
    {
        "Короткий URL": 1,
        "Средний": 0,
        "Слишком длинный (подозрительно)": -1
    }
)

ShortURL = feature(
    "Используется сокращённая ссылка?",
    {
        "Нет": 1,
        "Иногда": 0,
        "Да (подозрительно)": -1
    }
)

Symbol_at = feature(
    "Есть символ @ в URL?",
    {
        "Нет": 1,
        "Редко": 0,
        "Да (опасно)": -1
    }
)

Redirecting = feature(
    "Есть скрытые редиректы (//)?",
    {
        "Нет": 1,
        "Иногда": 0,
        "Да": -1
    }
)

PrefixSuffix = feature(
    "Есть дефисы в домене?",
    {
        "Нет": 1,
        "Один": 0,
        "Много (подозрительно)": -1
    }
)

SubDomains = feature(
    "Количество поддоменов",
    {
        "Один домен": 1,
        "2-3 поддомена": 0,
        "Много поддоменов (подозрительно)": -1
    }
)

HTTPS = feature(
    "Используется HTTPS?",
    {
        "Да": 1,
        "Частично": 0,
        "Нет (опасно)": -1
    }
)

DomainRegLen = feature(
    "Срок регистрации домена",
    {
        "Долгий срок": 1,
        "Средний": 0,
        "Короткий (подозрительно)": -1
    }
)

Favicon = feature(
    "Favicon сайта",
    {
        "Оригинальный": 1,
        "Необычный": 0,
        "Подозрительный": -1
    }
)

NonStdPort = feature("Нестандартный порт?", {"Нет": 1, "Иногда": 0, "Да": -1})
HTTPSDomainURL = feature("HTTPS в домене?", {"Нет": 1, "Иногда": 0, "Да": -1})
RequestURL = feature("Внешние запросы?", {"Нет": 1, "Смешанные": 0, "Много": -1})
AnchorURL = feature("Ссылки на сайте?", {"Нормальные": 1, "Смешанные": 0, "Подозрительные": -1})

LinksInScriptTags = feature("Скрипты?", {"Чистые": 1, "Смешанные": 0, "Подозрительные": -1})
ServerFormHandler = feature("Формы отправки данных?", {"Безопасные": 1, "Нейтральные": 0, "Подозрительные": -1})
InfoEmail = feature("Email на сайте?", {"Корпоративный": 1, "Обычный": 0, "Подозрительный": -1})
AbnormalURL = feature("Аномальный URL?", {"Нет": 1, "Иногда": 0, "Да": -1})

WebsiteForwarding = feature("Перенаправления?", {"Нет": 1, "Иногда": 0, "Часто": -1})
StatusBarCust = feature("Изменение статус-бара?", {"Нет": 1, "Иногда": 0, "Да": -1})

DisableRightClick = feature("Отключён правый клик?", {"Нет": 1, "Иногда": 0, "Да": -1})
UsingPopupWindow = feature("Попап окна?", {"Нет": 1, "Иногда": 0, "Часто": -1})
IframeRedirection = feature("Iframe редиректы?", {"Нет": 1, "Иногда": 0, "Да": -1})

AgeofDomain = feature("Возраст домена", {"Старый": 1, "Средний": 0, "Новый (риск)": -1})
DNSRecording = feature("DNS записи", {"Нормальные": 1, "Сомнительные": 0, "Плохие": -1})

WebsiteTraffic = feature("Трафик сайта", {"Высокий": 1, "Средний": 0, "Низкий (подозрительно)": -1})
PageRank = feature("PageRank", {"Высокий": 1, "Средний": 0, "Низкий": -1})

GoogleIndex = feature("Google Index", {"Есть в Google": 1, "Частично": 0, "Нет (опасно)": -1})

LinksPointingToPage = feature("Входящие ссылки", {"Много": 1, "Средне": 0, "Мало": -1})

StatsReport = feature("Статистические отчёты", {"Чистые": 1, "Сомнительные": 0, "Плохие": -1})


# ===== DATAFRAME =====
input_data = pd.DataFrame([[
    1,
    UsingIP, LongURL, ShortURL, Symbol_at, Redirecting,
    PrefixSuffix, SubDomains, HTTPS, DomainRegLen, Favicon,
    NonStdPort, HTTPSDomainURL, RequestURL, AnchorURL,
    LinksInScriptTags, ServerFormHandler, InfoEmail, AbnormalURL,
    WebsiteForwarding, StatusBarCust, DisableRightClick,
    UsingPopupWindow, IframeRedirection, AgeofDomain, DNSRecording,
    WebsiteTraffic, PageRank, GoogleIndex, LinksPointingToPage,
    StatsReport
]], columns=model.feature_names_in_)


# ===== PREDICT =====
if st.button("Проверить сайт"):

    prediction = model.predict(input_data)[0]
    proba = model.predict_proba(input_data)[0]

    st.subheader("Результат")

    if prediction == -1:
        st.error("ФИШИНГОВЫЙ САЙТ")
    else:
        st.success("БЕЗОПАСНЫЙ САЙТ")

    st.write(f"Вероятность безопасности: {proba[1]*100:.2f}%")
    st.write(f"Вероятность фишинга: {proba[0]*100:.2f}%")
