# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZbQScdH28kKLVbNmrDBXgo_EG_LI5sp
"""

import streamlit as st
import pandas as pd
import joblib

# Загрузка модели
model = joblib.load("phishing_model.pkl")

st.title("Phishing Website Detection")

st.write("Введите характеристики сайта")

having_IP_Address = st.selectbox(
    "Есть ли IP-адрес в URL?",
    [-1, 1]
)

URL_Length = st.selectbox(
    "Длина URL",
    [-1, 0, 1]
)

HTTPS = st.selectbox(
    "Используется HTTPS?",
    [-1, 1]
)

Domain_Age = st.selectbox(
    "Возраст домена",
    [-1, 1]
)

Subdomain_Count = st.selectbox(
    "Количество поддоменов",
    [-1, 0, 1]
)

# Создание DataFrame
input_data = pd.DataFrame({
    "having_IP_Address": [having_IP_Address],
    "URL_Length": [URL_Length],
    "Shortining_Service": [1],
    "having_At_Symbol": [1],
    "double_slash_redirecting": [1],
    "Prefix_Suffix": [1],
    "having_Sub_Domain": [Subdomain_Count],
    "SSLfinal_State": [HTTPS],
    "Domain_registeration_length": [Domain_Age],
    "Favicon": [1],
    "port": [1],
    "HTTPS_token": [1],
    "Request_URL": [1],
    "URL_of_Anchor": [1],
    "Links_in_tags": [1],
    "SFH": [1],
    "Submitting_to_email": [1],
    "Abnormal_URL": [1],
    "Redirect": [0],
    "on_mouseover": [1],
    "RightClick": [1],
    "popUpWidnow": [1],
    "Iframe": [1],
    "age_of_domain": [Domain_Age],
    "DNSRecord": [1],
    "web_traffic": [1],
    "Page_Rank": [1],
    "Google_Index": [1],
    "Links_pointing_to_page": [1],
    "Statistical_report": [1]
})

# Предсказание
if st.button("Check Website"):

    prediction = model.predict(input_data)

    if prediction[0] == -1:
        st.error("Phishing Website Detected")
    else:
        st.success("Website Looks Safe")