# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162ZJwpSIhCyYC9C2rxRzZ9rpwaKoWzWD
"""

from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import joblib

data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

model = RandomForestClassifier()

model.fit(X, y)

joblib.dump(model, 'breast_cancer_model.pkl')